on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  get-tag-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - id: get-tag-branches
        run: |
          BRANCH="$(git branch --remotes --contains ${{ github.ref }} | sed s/origin\\/// | tr -d '\n')"
          echo "branches=$BRANCH" >> $GITHUB_OUTPUT
    outputs:
      branches: ${{ steps.get-tag-branches.outputs.branches }}
  prepare:
    needs:
      - get-tag-branches
    if: contains(${{ needs.get-tag-branches.outputs.branches }}, 'main')
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} --draft --verify-tag --title ${{ github.ref_name }}
  build:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # 5.0.0
      - run: pnpm install
      - run: pnpm run build
      - run: echo PACKAGE_NAME=${{ github.event.repository.name }}.vsix >> $GITHUB_ENV
      - run: |
          if [[ $(echo ${{ github.ref_name }}) == *-* ]]; then
            pnpm exec vsce package --out $PACKAGE_NAME --pre-release
          else
            pnpm exec vsce package --out $PACKAGE_NAME
          fi
      - run: shasum -a 256 $PACKAGE_NAME > $PACKAGE_NAME.sha256
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} $PACKAGE_NAME $PACKAGE_NAME.sha256
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          if [[ $(echo ${{ github.ref_name }}) == *-* ]]; then
            pnpm exec vsce publish --packagePath $PACKAGE_NAME --pat ${{ secrets.VSCE_PAT }} --pre-release
          else
            pnpm exec vsce publish --packagePath $PACKAGE_NAME --pat ${{ secrets.VSCE_PAT }}
          fi
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit ${{ github.ref_name }} --draft=false
